### ISSUE TITLE
Support navigation between dashboards

### ISSUE THREAD

**Issue by rdenaux** [co-inform/dashboard-fe#3]
I think we should have several manually crafted dashboards for Co-inform (I'll propose a list dashboards to be developed elsewhere). Once we do this we will want to be able to configure each of our dashboards so that we can provide links between the dashboards. I tried drafting such a "navigation component" by simply adding a "Text" panel and editing markdown or html for it. Unfortunately, markdown didn't convert links to `a` html elements and the html formatter, removed the `href` attributes (for security reasons?).

Banana supports passing path params to load pre-configured dashboards. E.g. 
`https://dashboard.coinform.eu/#/dashboard?kbnType=file&kbnId=coinfo-doc-se.json` will try to load a dashboard stored on the webserver at `banana/app/dashboards/coinfo-doc-se.json`

**Comment by davidsalvador** [comment]
Sounds like a good idea. Maybe we could achieve this by setting different redirects in the NGINX server. For example:
- `https://dashboard.coinform.eu/policy-maker` redirects to `https://dashboard.coinform.eu/#/dashboard?kbnType=file&kbnId=policy-maker-dashboard.json`.
- `https://dashboard.coinform.eu/journalist` redirects to `https://dashboard.coinform.eu/#/dashboard?kbnType=file&kbnId=journalist`.

**Comment by daffyDukk** [comment]
I've set this up to /journalist and /policy-maker. At the moment the dashboards are empty/dark since there is no dashboard config for that. Once the correct config is included in the repo and pushed to the server it will work

**Comment by rdenaux** [comment]
The implemented solution solves the back-end side of things (we can link to specific paths). But the front-end still is not capable of displaying links, so I'm reopening until that is made possible (will probably require modifying Banana code). 

Ideally, I'd like to be able to add a Text component and write markdown to explain what the dashboard is showing and add [links](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links) to other dashboards. If that's not possible, I should be able to write the html `<a href=...></a>` elements.

**Comment by rdenaux** [comment]
This seems resolved now. Closing.
