### ISSUE TITLE
Continuous delivery of various co-inform dashboards

### ISSUE THREAD

**Issue by rdenaux** [co-inform/dashboard-fe#4]
Rather than having a single "co-inform" dashboard, it makes sense to have several. (We may want to have a default one which shows an overall overview, but this is currently difficult because it would need to gather data from several Solr collections). An initial list of separate dashboards is:

* Documents
  * Austrian Pilot (news)
  * Greek Pilot (news)
  * Swedish Pilot (news)
  * Fact-checkers (articles by Fact-checkers as well as articles linked by fact-checkers, which may include documents used to support or disprove a claim as well as links to articles where the fact-checked claim appeared).
  * Satirical news
* Claims: extracted from collected news as well as from databases of reviewed claims
* Tweets:
  * manual accuracy ratings provided by co-informers
  * automatic credibility ratings for tweets seen by co-informers
* Tailor-made dashboards
  * Austrian Politics
  * Greek immigration
** Swedish Healthcare
   
Banana supports passing path params to load pre-configured dashboards. E.g. 
`https://dashboard.coinform.eu/#/dashboard?kbnType=file&kbnId=coinfo-doc-se.json` will try to load a dashboard stored on the webserver at `banana/app/dashboards/coinfo-doc-se.json`

**Comment by daffyDukk** [comment]
Ok. I've set the servers up for CI. Any PR into the production branch with a confirmed review will be automatically pulled to the server.
At the moment there are 3 paths working. The standard one, /journalist and /policy-maker. If we need more paths I need info so I can set that up. At the moment /journalist and policy-maker only returns black/empty screens since there are no dashboard json files for them.

**Comment by daffyDukk** [comment]
If that is enough for now you can close this issue

**Comment by rdenaux** [comment]
Great that this technical solution is set up now. Two things though:

1. David's endpoint proposals were just examples. Unfortunately I don't think we can/should make generic dashboards for *journalists* and *policy-makers*. See my initial proposal (above) of dashboards that make sense based on the databases we have (at the moment I think Banana cannot create a dashboard that talks to 2 or more backend collections). All the docs and claims dashboards are suitable to both policy-makers and journalists of the specific countries or in general. Anyway, if we agree on the list of dashboards we'll a list of paths like:
   * /docs/austrian-pilot
   * /docs/greek-pilot
   * /docs/swedish-pilot
   * /docs/fact-checkers
   * ~~/docs/satirical~~ (experimental collection, probably best to leave if for now)
   * /claims
   * /tweet/user-ratings
   * /tweet/tagged
   * /austria/politics (or /politics/austria ?)
   * /greece/immigration
   * /sweden/healthcare

2. Where exactly do we need to put the banana json files? What is the name mapping between the json file and the paths where they'll be published?

**Comment by daffyDukk** [comment]
The json files should be put in the src/app/dashboards folder of the repo. The name mapping can be anything we decide. At the moment I'm hardcoding the webserver to point to certain files depending of what endpoint the user hits under dashboard.coinform.eu. I'm trying to figure a scheme for automatically doing this so I dont have to hardcode it

**Comment by daffyDukk** [comment]
Server updated to handle three levels after /db ie /db/politics/sweden/stockholm
Separator can be - or / after the initial /db ie /db/politics-sweden-stockholm will translate to the same json document as the previous

**Comment by rdenaux** [comment]
Besides this redirect, Banana allows access to dashboards simply by using `/file/nameOfDashboard.json`, which is simpler and supported out of the box.
